### ISSUE TITLE
Doesnt work on Members

### ISSUE THREAD

**Issue by rasmuseeg** [umco/umbraco-vorto#63]
Hi There, awesome editor. Though i can't get it to work with any datatypes on a member?

I found the following code returns null.

```
vortoResources.getDataTypeByAlias(currentSection, nodeContext.contentTypeAlias, $scope.model.alias).then(function (dataType2) {
                $scope.model.value.dtdGuid = dataType2.guid;
```

At this point dataType2 is _"null"_

**Comment by mattbrailsford** [comment]
Vorto is currently only built to work on Content / Media. I'd need to check what else we need to do, but it may just need us to add another option to this switch statement for member:

https://github.com/umco/umbraco-vorto/blob/master/src/Our.Umbraco.Vorto/Web/Controllers/VortoApiController.cs#L44

If you wanted to pull the code and compile a custom version to check, and create a Pull Request if that does do the trick, that would be awesome. Otherwise I'll try and take a look as soon as I can.

**Comment by rasmuseeg** [comment]
Okay, i was going to make a property editor either anyways. Will look into it.

**Comment by mattbrailsford** [comment]
Thanks Rasmus, any help would be appreciated.

**Comment by rasmuseeg** [comment]
Updated the package, and now it breaks again.

the returned datatype on:
https://github.com/umco/umbraco-vorto/blob/master/src/Our.Umbraco.Vorto/Web/UI/App_Plugins/Vorto/js/vorto.js#L313 
Is null again.
